spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/sweater?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.generate-ddl=false
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=validate


spring.freemarker.expose-request-attributes=true
spring.freemarker.suffix= .ftl

## это ссылка/путь к файлам
upload.path=//C:/Users/nikit/IdeaProjects/sweater/src/uploads

spring.mail.host=smtp.yandex.ru
spring.mail.username=n.shebin@yandex.ru
spring.mail.password=shebinnikita1990
spring.mail.port=465
spring.mail.protocol=smtps
mail.debug=true
